#!/bin/sh

install_brew() {
  # Proudly borrowed from:
  # https://github.com/duckfullstop/dotfiles/blob/f734eea399a7ccd1c25b57242997e79f230abc4d/.config/yadm/bootstrap

  # install Homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating Homebrew bundle"
    brew bundle --global
  fi
}

install_iterm() {
    # Assume we're on macOS
    brew install --cask iterm2
    if [ -d "$HOME/.config/iterm2" ]; then
        echo "Setting iTerm preference folder"
        defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
    fi
}

echo_reminders() {
    echo "Install iTerm2 auto dark mode: (download and run) https://iterm2.com/python-api/examples/theme.html"
}

install_brew

system_type=$(uname -s)
if [ "$system_type" = "Darwin" ]; then
    install_iterm
fi

echo_reminders

echo "Welcome to your new system"
